name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:
 
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: false
env:
  AWS_REGION: us-east-1                  

permissions:
  id-token: write
  contents: read


jobs:
  deploy:
    name: Nodes Deployment TST
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::914509617440:role/iams-ci-global
        role-session-name: githubactionssession
        aws-region: ${{ env.AWS_REGION }}

    - name: Test
      run: aws s3 ls

  matrix-networks:
    name: Blockchain Network Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest]
        compiler: [ {cpp: g++, c: gcc}, {cpp: g++-8, c: gcc-8}, {cpp: clang++, c: clang} ]
    steps:
      - name: Compile with C++ compiler
        run: echo ${{ matrix.compiler.cpp }}
      - name: Compile with C compiler
        run: echo ${{ matrix.compiler.c }} 
